// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonApi.Data;

#nullable disable

namespace ETEC_DS_POKEMON.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240618182909_StructureCreate")]
    partial class StructureCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokemonApi.Models.Habilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("PP")
                        .HasColumnType("int");

                    b.Property<int>("Poder")
                        .HasColumnType("int");

                    b.Property<int>("Precisao")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_HABILIDADES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Um ataque corporal comum.",
                            Nome = "Tackle",
                            PP = 35,
                            Poder = 40,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Reduz o Ataque do oponente.",
                            Nome = "Growl",
                            PP = 40,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Ataca com vinhas ou chicotes.",
                            Nome = "Vine Whip",
                            PP = 25,
                            Poder = 45,
                            Precisao = 100,
                            Tipo = 9
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Lâminas de folha são lançadas como navalhas.",
                            Nome = "Razor Leaf",
                            PP = 25,
                            Poder = 55,
                            Precisao = 95,
                            Tipo = 9
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Ataque com uma rajada de fogo intenso.",
                            Nome = "Flamethrower",
                            PP = 15,
                            Poder = 90,
                            Precisao = 100,
                            Tipo = 6
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Envolve o oponente em chamas por 2 a 5 turnos.",
                            Nome = "Fire Spin",
                            PP = 15,
                            Poder = 35,
                            Precisao = 85,
                            Tipo = 6
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Um ataque cortante com alta chance de acerto crítico.",
                            Nome = "Slash",
                            PP = 20,
                            Poder = 70,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Atira água com pressão no oponente.",
                            Nome = "Water Gun",
                            PP = 25,
                            Poder = 40,
                            Precisao = 100,
                            Tipo = 17
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Atira um jato de água poderoso no oponente.",
                            Nome = "Hydro Pump",
                            PP = 5,
                            Poder = 110,
                            Precisao = 80,
                            Tipo = 17
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Ataque com uma onda gigante. Pode ser usado fora de batalha para atravessar a água.",
                            Nome = "Surf",
                            PP = 15,
                            Poder = 90,
                            Precisao = 100,
                            Tipo = 17
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "Ataque elétrico com chance de paralisar o oponente.",
                            Nome = "Thunderbolt",
                            PP = 15,
                            Poder = 90,
                            Precisao = 100,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 12,
                            Descricao = "Ataque elétrico poderoso com chance de paralisar o oponente.",
                            Nome = "Thunder",
                            PP = 10,
                            Poder = 110,
                            Precisao = 70,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 13,
                            Descricao = "Paralisa o oponente.",
                            Nome = "Thunder Wave",
                            PP = 20,
                            Poder = 0,
                            Precisao = 90,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 14,
                            Descricao = "Cava um buraco no primeiro turno e ataca no segundo.",
                            Nome = "Dig",
                            PP = 10,
                            Poder = 80,
                            Precisao = 100,
                            Tipo = 10
                        },
                        new
                        {
                            Id = 15,
                            Descricao = "Um terremoto que atinge todos os Pokémon em campo.",
                            Nome = "Earthquake",
                            PP = 10,
                            Poder = 100,
                            Precisao = 100,
                            Tipo = 10
                        },
                        new
                        {
                            Id = 16,
                            Descricao = "Ataque psíquico que pode confundir o oponente.",
                            Nome = "Confusion",
                            PP = 25,
                            Poder = 50,
                            Precisao = 100,
                            Tipo = 14
                        },
                        new
                        {
                            Id = 17,
                            Descricao = "Ataque psíquico poderoso que pode abaixar a Defesa Especial do oponente.",
                            Nome = "Psychic",
                            PP = 10,
                            Poder = 90,
                            Precisao = 100,
                            Tipo = 14
                        },
                        new
                        {
                            Id = 18,
                            Descricao = "Faz o oponente dormir.",
                            Nome = "Hypnosis",
                            PP = 20,
                            Poder = 0,
                            Precisao = 60,
                            Tipo = 14
                        },
                        new
                        {
                            Id = 19,
                            Descricao = "Ataque que suga a vida do oponente.",
                            Nome = "Leech Life",
                            PP = 10,
                            Poder = 80,
                            Precisao = 100,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 20,
                            Descricao = "Ataque ácido que pode abaixar a Defesa do oponente.",
                            Nome = "Acid",
                            PP = 30,
                            Poder = 40,
                            Precisao = 100,
                            Tipo = 13
                        },
                        new
                        {
                            Id = 21,
                            Descricao = "Ataque com chamas pequenas. Pode queimar o oponente.",
                            Nome = "Ember",
                            PP = 25,
                            Poder = 40,
                            Precisao = 100,
                            Tipo = 6
                        },
                        new
                        {
                            Id = 22,
                            Descricao = "Ataque com uma bola de fogo que pode queimar o oponente.",
                            Nome = "Fire Blast",
                            PP = 5,
                            Poder = 110,
                            Precisao = 85,
                            Tipo = 6
                        },
                        new
                        {
                            Id = 23,
                            Descricao = "Aumenta o Ataque a cada turno que é atingido.",
                            Nome = "Rage",
                            PP = 20,
                            Poder = 20,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 24,
                            Descricao = "Foge da batalha selvagem ou de uma batalha de treinador.",
                            Nome = "Teleport",
                            PP = 20,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 14
                        },
                        new
                        {
                            Id = 25,
                            Descricao = "Ataque fantasma que causa dano igual ao nível do usuário.",
                            Nome = "Night Shade",
                            PP = 15,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 8
                        },
                        new
                        {
                            Id = 26,
                            Descricao = "Copia a última habilidade usada pelo oponente.",
                            Nome = "Mimic",
                            PP = 10,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 27,
                            Descricao = "Reduz a Defesa do oponente.",
                            Nome = "Screech",
                            PP = 40,
                            Poder = 0,
                            Precisao = 85,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 28,
                            Descricao = "Aumenta a evasão do usuário.",
                            Nome = "Double Team",
                            PP = 15,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 29,
                            Descricao = "Recupera metade dos pontos de vida do usuário.",
                            Nome = "Recover",
                            PP = 10,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 30,
                            Descricao = "Aumenta a Defesa do usuário.",
                            Nome = "Harden",
                            PP = 30,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 31,
                            Descricao = "Aumenta a evasão do usuário.",
                            Nome = "Minimize",
                            PP = 20,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 32,
                            Descricao = "Reduz a precisão do oponente.",
                            Nome = "Smokescreen",
                            PP = 20,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 33,
                            Descricao = "Confunde o oponente.",
                            Nome = "Confuse Ray",
                            PP = 10,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 8
                        },
                        new
                        {
                            Id = 34,
                            Descricao = "Aumenta a Defesa do usuário.",
                            Nome = "Withdraw",
                            PP = 40,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 17
                        },
                        new
                        {
                            Id = 35,
                            Descricao = "Aumenta a Defesa do usuário.",
                            Nome = "Barrier",
                            PP = 20,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 14
                        },
                        new
                        {
                            Id = 36,
                            Descricao = "Reduz o dano de ataques especiais do oponente.",
                            Nome = "Light Screen",
                            PP = 30,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 14
                        },
                        new
                        {
                            Id = 37,
                            Descricao = "Remove todas as alterações de status.",
                            Nome = "Haze",
                            PP = 30,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 11
                        },
                        new
                        {
                            Id = 38,
                            Descricao = "Reduz o dano de ataques físicos do oponente.",
                            Nome = "Reflect",
                            PP = 20,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 14
                        },
                        new
                        {
                            Id = 39,
                            Descricao = "Atira pedras no oponente. Pode reduzir a velocidade do oponente.",
                            Nome = "Rock Tomb",
                            PP = 15,
                            Poder = 60,
                            Precisao = 95,
                            Tipo = 15
                        },
                        new
                        {
                            Id = 40,
                            Descricao = "Aumenta a Defesa do usuário.",
                            Nome = "Defense Curl",
                            PP = 40,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 41,
                            Descricao = "Aumenta a chance de acerto crítico.",
                            Nome = "Focus Energy",
                            PP = 30,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 42,
                            Descricao = "Guarda energia por 2 a 3 turnos e depois ataca.",
                            Nome = "Bide",
                            PP = 10,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 43,
                            Descricao = "Usa um ataque aleatório.",
                            Nome = "Metronome",
                            PP = 10,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 44,
                            Descricao = "Copia o último ataque usado pelo oponente.",
                            Nome = "Mirror Move",
                            PP = 20,
                            Poder = 0,
                            Precisao = 100,
                            Tipo = 7
                        },
                        new
                        {
                            Id = 45,
                            Descricao = "Causa dano ao usuário e ao oponente.",
                            Nome = "Self-Destruct",
                            PP = 5,
                            Poder = 200,
                            Precisao = 100,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 46,
                            Descricao = "Atira ovos no oponente.",
                            Nome = "Egg Bomb",
                            PP = 10,
                            Poder = 100,
                            Precisao = 75,
                            Tipo = 12
                        },
                        new
                        {
                            Id = 47,
                            Descricao = "Ataque com a língua. Pode paralisar o oponente.",
                            Nome = "Lick",
                            PP = 30,
                            Poder = 20,
                            Precisao = 100,
                            Tipo = 8
                        },
                        new
                        {
                            Id = 48,
                            Descricao = "Ataque de fumaça venenosa. Pode envenenar o oponente.",
                            Nome = "Smog",
                            PP = 20,
                            Poder = 30,
                            Precisao = 70,
                            Tipo = 13
                        },
                        new
                        {
                            Id = 49,
                            Descricao = "Ataque de lodo venenoso. Pode envenenar o oponente.",
                            Nome = "Sludge",
                            PP = 20,
                            Poder = 65,
                            Precisao = 100,
                            Tipo = 13
                        },
                        new
                        {
                            Id = 50,
                            Descricao = "Ataque com um osso. Pode causar acerto crítico.",
                            Nome = "Bone Club",
                            PP = 20,
                            Poder = 65,
                            Precisao = 85,
                            Tipo = 10
                        },
                        new
                        {
                            Id = 51,
                            Descricao = "Ataque de soco em chamas. Pode queimar o oponente.",
                            Nome = "Fire Punch",
                            PP = 15,
                            Poder = 75,
                            Precisao = 100,
                            Tipo = 6
                        },
                        new
                        {
                            Id = 52,
                            Descricao = "Ataque de soco congelante. Pode congelar o oponente.",
                            Nome = "Ice Punch",
                            PP = 15,
                            Poder = 75,
                            Precisao = 100,
                            Tipo = 11
                        },
                        new
                        {
                            Id = 53,
                            Descricao = "Ataque de soco elétrico. Pode paralisar o oponente.",
                            Nome = "Thunder Punch",
                            PP = 15,
                            Poder = 75,
                            Precisao = 100,
                            Tipo = 3
                        },
                        new
                        {
                            Id = 54,
                            Descricao = "Causa 40 pontos de dano.",
                            Nome = "Dragon Rage",
                            PP = 10,
                            Poder = 40,
                            Precisao = 100,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 55,
                            Descricao = "Prende o oponente por 2 a 5 turnos.",
                            Nome = "Bind",
                            PP = 20,
                            Poder = 15,
                            Precisao = 85,
                            Tipo = 12
                        });
                });

            modelBuilder.Entity("PokemonApi.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TB_POKEMONS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Altura = 0.69999999999999996,
                            Genero = "",
                            Nome = "Bulbasaur",
                            Peso = 6.9000000000000004,
                            Tipo = "[9,13]"
                        },
                        new
                        {
                            Id = 2,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Ivysaur",
                            Peso = 13.0,
                            Tipo = "[9,13]"
                        },
                        new
                        {
                            Id = 3,
                            Altura = 2.0,
                            Genero = "",
                            Nome = "Venusaur",
                            Peso = 100.0,
                            Tipo = "[9,13]"
                        },
                        new
                        {
                            Id = 4,
                            Altura = 0.59999999999999998,
                            Genero = "",
                            Nome = "Charmander",
                            Peso = 8.5,
                            Tipo = "[6]"
                        },
                        new
                        {
                            Id = 5,
                            Altura = 1.1000000000000001,
                            Genero = "",
                            Nome = "Charmeleon",
                            Peso = 19.0,
                            Tipo = "[6]"
                        },
                        new
                        {
                            Id = 6,
                            Altura = 1.7,
                            Genero = "",
                            Nome = "Charizard",
                            Peso = 90.5,
                            Tipo = "[6,7]"
                        },
                        new
                        {
                            Id = 7,
                            Altura = 0.5,
                            Genero = "",
                            Nome = "Squirtle",
                            Peso = 9.0,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 8,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Wartortle",
                            Peso = 22.5,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 9,
                            Altura = 1.6000000000000001,
                            Genero = "",
                            Nome = "Blastoise",
                            Peso = 85.5,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 10,
                            Altura = 0.29999999999999999,
                            Genero = "",
                            Nome = "Caterpie",
                            Peso = 2.8999999999999999,
                            Tipo = "[0]"
                        },
                        new
                        {
                            Id = 11,
                            Altura = 0.69999999999999996,
                            Genero = "",
                            Nome = "Metapod",
                            Peso = 9.9000000000000004,
                            Tipo = "[0]"
                        },
                        new
                        {
                            Id = 12,
                            Altura = 1.1000000000000001,
                            Genero = "",
                            Nome = "Butterfree",
                            Peso = 32.0,
                            Tipo = "[0,7]"
                        },
                        new
                        {
                            Id = 13,
                            Altura = 0.29999999999999999,
                            Genero = "",
                            Nome = "Weedle",
                            Peso = 3.2000000000000002,
                            Tipo = "[0,13]"
                        },
                        new
                        {
                            Id = 14,
                            Altura = 0.59999999999999998,
                            Genero = "",
                            Nome = "Kakuna",
                            Peso = 10.0,
                            Tipo = "[0,13]"
                        },
                        new
                        {
                            Id = 15,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Beedrill",
                            Peso = 29.5,
                            Tipo = "[0,13]"
                        },
                        new
                        {
                            Id = 16,
                            Altura = 0.29999999999999999,
                            Genero = "",
                            Nome = "Pidgey",
                            Peso = 1.8,
                            Tipo = "[12,7]"
                        },
                        new
                        {
                            Id = 17,
                            Altura = 1.1000000000000001,
                            Genero = "",
                            Nome = "Pidgeotto",
                            Peso = 30.0,
                            Tipo = "[12,7]"
                        },
                        new
                        {
                            Id = 18,
                            Altura = 1.5,
                            Genero = "",
                            Nome = "Pidgeot",
                            Peso = 39.5,
                            Tipo = "[12,7]"
                        },
                        new
                        {
                            Id = 19,
                            Altura = 0.29999999999999999,
                            Genero = "",
                            Nome = "Rattata",
                            Peso = 3.5,
                            Tipo = "[12]"
                        },
                        new
                        {
                            Id = 20,
                            Altura = 0.69999999999999996,
                            Genero = "",
                            Nome = "Raticate",
                            Peso = 18.5,
                            Tipo = "[12]"
                        },
                        new
                        {
                            Id = 21,
                            Altura = 0.29999999999999999,
                            Genero = "",
                            Nome = "Spearow",
                            Peso = 2.0,
                            Tipo = "[12,7]"
                        },
                        new
                        {
                            Id = 22,
                            Altura = 1.2,
                            Genero = "",
                            Nome = "Fearow",
                            Peso = 38.0,
                            Tipo = "[12,7]"
                        },
                        new
                        {
                            Id = 23,
                            Altura = 2.0,
                            Genero = "",
                            Nome = "Ekans",
                            Peso = 6.9000000000000004,
                            Tipo = "[13]"
                        },
                        new
                        {
                            Id = 24,
                            Altura = 3.5,
                            Genero = "",
                            Nome = "Arbok",
                            Peso = 65.0,
                            Tipo = "[13]"
                        },
                        new
                        {
                            Id = 25,
                            Altura = 0.40000000000000002,
                            Genero = "",
                            Nome = "Pikachu",
                            Peso = 6.0,
                            Tipo = "[3]"
                        },
                        new
                        {
                            Id = 26,
                            Altura = 0.80000000000000004,
                            Genero = "",
                            Nome = "Raichu",
                            Peso = 30.0,
                            Tipo = "[3]"
                        },
                        new
                        {
                            Id = 27,
                            Altura = 0.59999999999999998,
                            Genero = "",
                            Nome = "Sandshrew",
                            Peso = 12.0,
                            Tipo = "[10]"
                        },
                        new
                        {
                            Id = 28,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Sandslash",
                            Peso = 29.5,
                            Tipo = "[10]"
                        },
                        new
                        {
                            Id = 29,
                            Altura = 0.40000000000000002,
                            Genero = "",
                            Nome = "Nidoran♀",
                            Peso = 7.0,
                            Tipo = "[13]"
                        },
                        new
                        {
                            Id = 30,
                            Altura = 0.80000000000000004,
                            Genero = "",
                            Nome = "Nidorina",
                            Peso = 20.0,
                            Tipo = "[13]"
                        },
                        new
                        {
                            Id = 31,
                            Altura = 1.3,
                            Genero = "",
                            Nome = "Nidoqueen",
                            Peso = 60.0,
                            Tipo = "[13,10]"
                        },
                        new
                        {
                            Id = 32,
                            Altura = 0.5,
                            Genero = "",
                            Nome = "Nidoran♂",
                            Peso = 9.0,
                            Tipo = "[13]"
                        },
                        new
                        {
                            Id = 33,
                            Altura = 0.90000000000000002,
                            Genero = "",
                            Nome = "Nidorino",
                            Peso = 19.5,
                            Tipo = "[13]"
                        },
                        new
                        {
                            Id = 34,
                            Altura = 1.3999999999999999,
                            Genero = "",
                            Nome = "Nidoking",
                            Peso = 62.0,
                            Tipo = "[13,10]"
                        },
                        new
                        {
                            Id = 35,
                            Altura = 0.59999999999999998,
                            Genero = "",
                            Nome = "Clefairy",
                            Peso = 7.5,
                            Tipo = "[4]"
                        },
                        new
                        {
                            Id = 36,
                            Altura = 1.3,
                            Genero = "",
                            Nome = "Clefable",
                            Peso = 40.0,
                            Tipo = "[4]"
                        },
                        new
                        {
                            Id = 37,
                            Altura = 0.59999999999999998,
                            Genero = "",
                            Nome = "Vulpix",
                            Peso = 9.9000000000000004,
                            Tipo = "[6]"
                        },
                        new
                        {
                            Id = 38,
                            Altura = 1.1000000000000001,
                            Genero = "",
                            Nome = "Ninetales",
                            Peso = 19.899999999999999,
                            Tipo = "[6]"
                        },
                        new
                        {
                            Id = 39,
                            Altura = 0.5,
                            Genero = "",
                            Nome = "Jigglypuff",
                            Peso = 5.5,
                            Tipo = "[12,4]"
                        },
                        new
                        {
                            Id = 40,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Wigglytuff",
                            Peso = 12.0,
                            Tipo = "[12,4]"
                        },
                        new
                        {
                            Id = 41,
                            Altura = 0.80000000000000004,
                            Genero = "",
                            Nome = "Zubat",
                            Peso = 7.5,
                            Tipo = "[7,13]"
                        },
                        new
                        {
                            Id = 42,
                            Altura = 1.6000000000000001,
                            Genero = "",
                            Nome = "Golbat",
                            Peso = 55.0,
                            Tipo = "[7,13]"
                        },
                        new
                        {
                            Id = 43,
                            Altura = 0.5,
                            Genero = "",
                            Nome = "Oddish",
                            Peso = 5.4000000000000004,
                            Tipo = "[9,13]"
                        },
                        new
                        {
                            Id = 44,
                            Altura = 0.80000000000000004,
                            Genero = "",
                            Nome = "Gloom",
                            Peso = 8.5999999999999996,
                            Tipo = "[9,13]"
                        },
                        new
                        {
                            Id = 45,
                            Altura = 1.2,
                            Genero = "",
                            Nome = "Vileplume",
                            Peso = 18.600000000000001,
                            Tipo = "[9,13]"
                        },
                        new
                        {
                            Id = 46,
                            Altura = 0.29999999999999999,
                            Genero = "",
                            Nome = "Paras",
                            Peso = 5.4000000000000004,
                            Tipo = "[0,9]"
                        },
                        new
                        {
                            Id = 47,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Parasect",
                            Peso = 29.5,
                            Tipo = "[0,9]"
                        },
                        new
                        {
                            Id = 48,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Venonat",
                            Peso = 30.0,
                            Tipo = "[0,13]"
                        },
                        new
                        {
                            Id = 49,
                            Altura = 1.5,
                            Genero = "",
                            Nome = "Venomoth",
                            Peso = 12.5,
                            Tipo = "[0,13]"
                        },
                        new
                        {
                            Id = 50,
                            Altura = 0.20000000000000001,
                            Genero = "",
                            Nome = "Diglett",
                            Peso = 0.80000000000000004,
                            Tipo = "[10]"
                        },
                        new
                        {
                            Id = 51,
                            Altura = 0.69999999999999996,
                            Genero = "",
                            Nome = "Dugtrio",
                            Peso = 33.299999999999997,
                            Tipo = "[10]"
                        },
                        new
                        {
                            Id = 52,
                            Altura = 0.40000000000000002,
                            Genero = "",
                            Nome = "Meowth",
                            Peso = 4.2000000000000002,
                            Tipo = "[12]"
                        },
                        new
                        {
                            Id = 53,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Persian",
                            Peso = 32.0,
                            Tipo = "[12]"
                        },
                        new
                        {
                            Id = 54,
                            Altura = 0.80000000000000004,
                            Genero = "",
                            Nome = "Psyduck",
                            Peso = 19.600000000000001,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 55,
                            Altura = 1.7,
                            Genero = "",
                            Nome = "Golduck",
                            Peso = 76.599999999999994,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 56,
                            Altura = 0.5,
                            Genero = "",
                            Nome = "Mankey",
                            Peso = 28.0,
                            Tipo = "[5]"
                        },
                        new
                        {
                            Id = 57,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Primeape",
                            Peso = 32.0,
                            Tipo = "[5]"
                        },
                        new
                        {
                            Id = 58,
                            Altura = 0.69999999999999996,
                            Genero = "",
                            Nome = "Growlithe",
                            Peso = 19.0,
                            Tipo = "[6]"
                        },
                        new
                        {
                            Id = 59,
                            Altura = 1.8999999999999999,
                            Genero = "",
                            Nome = "Arcanine",
                            Peso = 155.0,
                            Tipo = "[6]"
                        },
                        new
                        {
                            Id = 60,
                            Altura = 0.59999999999999998,
                            Genero = "",
                            Nome = "Poliwag",
                            Peso = 12.4,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 61,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Poliwhirl",
                            Peso = 20.0,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 62,
                            Altura = 1.3,
                            Genero = "",
                            Nome = "Poliwrath",
                            Peso = 54.0,
                            Tipo = "[17,5]"
                        },
                        new
                        {
                            Id = 63,
                            Altura = 0.90000000000000002,
                            Genero = "",
                            Nome = "Abra",
                            Peso = 19.5,
                            Tipo = "[14]"
                        },
                        new
                        {
                            Id = 64,
                            Altura = 1.3,
                            Genero = "",
                            Nome = "Kadabra",
                            Peso = 56.5,
                            Tipo = "[14]"
                        },
                        new
                        {
                            Id = 65,
                            Altura = 1.5,
                            Genero = "",
                            Nome = "Alakazam",
                            Peso = 48.0,
                            Tipo = "[14]"
                        },
                        new
                        {
                            Id = 66,
                            Altura = 0.80000000000000004,
                            Genero = "",
                            Nome = "Machop",
                            Peso = 19.5,
                            Tipo = "[5]"
                        },
                        new
                        {
                            Id = 67,
                            Altura = 1.5,
                            Genero = "",
                            Nome = "Machoke",
                            Peso = 70.5,
                            Tipo = "[5]"
                        },
                        new
                        {
                            Id = 68,
                            Altura = 1.6000000000000001,
                            Genero = "",
                            Nome = "Machamp",
                            Peso = 130.0,
                            Tipo = "[5]"
                        },
                        new
                        {
                            Id = 69,
                            Altura = 0.69999999999999996,
                            Genero = "",
                            Nome = "Bellsprout",
                            Peso = 4.0,
                            Tipo = "[9,13]"
                        },
                        new
                        {
                            Id = 70,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Weepinbell",
                            Peso = 6.4000000000000004,
                            Tipo = "[9,13]"
                        },
                        new
                        {
                            Id = 71,
                            Altura = 1.7,
                            Genero = "",
                            Nome = "Victreebel",
                            Peso = 15.5,
                            Tipo = "[9,13]"
                        },
                        new
                        {
                            Id = 72,
                            Altura = 0.90000000000000002,
                            Genero = "",
                            Nome = "Tentacool",
                            Peso = 45.5,
                            Tipo = "[17,13]"
                        },
                        new
                        {
                            Id = 73,
                            Altura = 1.6000000000000001,
                            Genero = "",
                            Nome = "Tentacruel",
                            Peso = 55.0,
                            Tipo = "[17,13]"
                        },
                        new
                        {
                            Id = 74,
                            Altura = 0.40000000000000002,
                            Genero = "",
                            Nome = "Geodude",
                            Peso = 20.0,
                            Tipo = "[15,10]"
                        },
                        new
                        {
                            Id = 75,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Graveler",
                            Peso = 105.0,
                            Tipo = "[15,10]"
                        },
                        new
                        {
                            Id = 76,
                            Altura = 1.3999999999999999,
                            Genero = "",
                            Nome = "Golem",
                            Peso = 300.0,
                            Tipo = "[15,10]"
                        },
                        new
                        {
                            Id = 77,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Ponyta",
                            Peso = 30.0,
                            Tipo = "[6]"
                        },
                        new
                        {
                            Id = 78,
                            Altura = 1.7,
                            Genero = "",
                            Nome = "Rapidash",
                            Peso = 95.0,
                            Tipo = "[6]"
                        },
                        new
                        {
                            Id = 79,
                            Altura = 1.2,
                            Genero = "",
                            Nome = "Slowpoke",
                            Peso = 36.0,
                            Tipo = "[17,14]"
                        },
                        new
                        {
                            Id = 80,
                            Altura = 1.6000000000000001,
                            Genero = "",
                            Nome = "Slowbro",
                            Peso = 78.5,
                            Tipo = "[17,14]"
                        },
                        new
                        {
                            Id = 81,
                            Altura = 0.29999999999999999,
                            Genero = "",
                            Nome = "Magnemite",
                            Peso = 6.0,
                            Tipo = "[3,16]"
                        },
                        new
                        {
                            Id = 82,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Magneton",
                            Peso = 60.0,
                            Tipo = "[3,16]"
                        },
                        new
                        {
                            Id = 83,
                            Altura = 0.80000000000000004,
                            Genero = "",
                            Nome = "Farfetch'd",
                            Peso = 15.0,
                            Tipo = "[12,7]"
                        },
                        new
                        {
                            Id = 84,
                            Altura = 1.3999999999999999,
                            Genero = "",
                            Nome = "Doduo",
                            Peso = 39.200000000000003,
                            Tipo = "[12,7]"
                        },
                        new
                        {
                            Id = 85,
                            Altura = 1.8,
                            Genero = "",
                            Nome = "Dodrio",
                            Peso = 85.200000000000003,
                            Tipo = "[12,7]"
                        },
                        new
                        {
                            Id = 86,
                            Altura = 1.1000000000000001,
                            Genero = "",
                            Nome = "Seel",
                            Peso = 90.0,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 87,
                            Altura = 1.7,
                            Genero = "",
                            Nome = "Dewgong",
                            Peso = 120.0,
                            Tipo = "[17,11]"
                        },
                        new
                        {
                            Id = 88,
                            Altura = 0.90000000000000002,
                            Genero = "",
                            Nome = "Grimer",
                            Peso = 30.0,
                            Tipo = "[13]"
                        },
                        new
                        {
                            Id = 89,
                            Altura = 1.2,
                            Genero = "",
                            Nome = "Muk",
                            Peso = 30.0,
                            Tipo = "[13]"
                        },
                        new
                        {
                            Id = 90,
                            Altura = 0.29999999999999999,
                            Genero = "",
                            Nome = "Shellder",
                            Peso = 4.0,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 91,
                            Altura = 1.5,
                            Genero = "",
                            Nome = "Cloyster",
                            Peso = 132.5,
                            Tipo = "[17,11]"
                        },
                        new
                        {
                            Id = 92,
                            Altura = 1.3,
                            Genero = "",
                            Nome = "Gastly",
                            Peso = 0.10000000000000001,
                            Tipo = "[8,13]"
                        },
                        new
                        {
                            Id = 93,
                            Altura = 1.6000000000000001,
                            Genero = "",
                            Nome = "Haunter",
                            Peso = 0.10000000000000001,
                            Tipo = "[8,13]"
                        },
                        new
                        {
                            Id = 94,
                            Altura = 1.5,
                            Genero = "",
                            Nome = "Gengar",
                            Peso = 40.5,
                            Tipo = "[8,13]"
                        },
                        new
                        {
                            Id = 95,
                            Altura = 8.8000000000000007,
                            Genero = "",
                            Nome = "Onix",
                            Peso = 210.0,
                            Tipo = "[15,10]"
                        },
                        new
                        {
                            Id = 96,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Drowzee",
                            Peso = 32.399999999999999,
                            Tipo = "[14]"
                        },
                        new
                        {
                            Id = 97,
                            Altura = 1.6000000000000001,
                            Genero = "",
                            Nome = "Hypno",
                            Peso = 75.599999999999994,
                            Tipo = "[14]"
                        },
                        new
                        {
                            Id = 98,
                            Altura = 0.40000000000000002,
                            Genero = "",
                            Nome = "Krabby",
                            Peso = 6.5,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 99,
                            Altura = 1.3,
                            Genero = "",
                            Nome = "Kingler",
                            Peso = 60.0,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 100,
                            Altura = 0.5,
                            Genero = "",
                            Nome = "Voltorb",
                            Peso = 10.4,
                            Tipo = "[3]"
                        },
                        new
                        {
                            Id = 101,
                            Altura = 1.2,
                            Genero = "",
                            Nome = "Electrode",
                            Peso = 66.599999999999994,
                            Tipo = "[3]"
                        },
                        new
                        {
                            Id = 102,
                            Altura = 0.40000000000000002,
                            Genero = "",
                            Nome = "Exeggcute",
                            Peso = 2.5,
                            Tipo = "[9,14]"
                        },
                        new
                        {
                            Id = 103,
                            Altura = 2.0,
                            Genero = "",
                            Nome = "Exeggutor",
                            Peso = 120.0,
                            Tipo = "[9,14]"
                        },
                        new
                        {
                            Id = 104,
                            Altura = 0.40000000000000002,
                            Genero = "",
                            Nome = "Cubone",
                            Peso = 6.5,
                            Tipo = "[10]"
                        },
                        new
                        {
                            Id = 105,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Marowak",
                            Peso = 45.0,
                            Tipo = "[10]"
                        },
                        new
                        {
                            Id = 106,
                            Altura = 1.5,
                            Genero = "",
                            Nome = "Hitmonlee",
                            Peso = 49.799999999999997,
                            Tipo = "[5]"
                        },
                        new
                        {
                            Id = 107,
                            Altura = 1.3999999999999999,
                            Genero = "",
                            Nome = "Hitmonchan",
                            Peso = 50.200000000000003,
                            Tipo = "[5]"
                        },
                        new
                        {
                            Id = 108,
                            Altura = 1.2,
                            Genero = "",
                            Nome = "Lickitung",
                            Peso = 65.5,
                            Tipo = "[12]"
                        },
                        new
                        {
                            Id = 109,
                            Altura = 0.59999999999999998,
                            Genero = "",
                            Nome = "Koffing",
                            Peso = 1.0,
                            Tipo = "[13]"
                        },
                        new
                        {
                            Id = 110,
                            Altura = 1.2,
                            Genero = "",
                            Nome = "Weezing",
                            Peso = 9.5,
                            Tipo = "[13]"
                        },
                        new
                        {
                            Id = 111,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Rhyhorn",
                            Peso = 115.0,
                            Tipo = "[10,15]"
                        },
                        new
                        {
                            Id = 112,
                            Altura = 1.8999999999999999,
                            Genero = "",
                            Nome = "Rhydon",
                            Peso = 120.0,
                            Tipo = "[10,15]"
                        },
                        new
                        {
                            Id = 113,
                            Altura = 1.1000000000000001,
                            Genero = "",
                            Nome = "Chansey",
                            Peso = 34.600000000000001,
                            Tipo = "[12]"
                        },
                        new
                        {
                            Id = 114,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Tangela",
                            Peso = 35.0,
                            Tipo = "[9]"
                        },
                        new
                        {
                            Id = 115,
                            Altura = 2.2000000000000002,
                            Genero = "",
                            Nome = "Kangaskhan",
                            Peso = 80.0,
                            Tipo = "[12]"
                        },
                        new
                        {
                            Id = 116,
                            Altura = 0.40000000000000002,
                            Genero = "",
                            Nome = "Horsea",
                            Peso = 8.0,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 117,
                            Altura = 1.2,
                            Genero = "",
                            Nome = "Seadra",
                            Peso = 25.0,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 118,
                            Altura = 0.59999999999999998,
                            Genero = "",
                            Nome = "Goldeen",
                            Peso = 15.0,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 119,
                            Altura = 1.3,
                            Genero = "",
                            Nome = "Seaking",
                            Peso = 39.0,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 120,
                            Altura = 0.80000000000000004,
                            Genero = "",
                            Nome = "Staryu",
                            Peso = 34.5,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 121,
                            Altura = 1.1000000000000001,
                            Genero = "",
                            Nome = "Starmie",
                            Peso = 80.0,
                            Tipo = "[17,14]"
                        },
                        new
                        {
                            Id = 122,
                            Altura = 1.3,
                            Genero = "",
                            Nome = "Mr. Mime",
                            Peso = 54.5,
                            Tipo = "[14]"
                        },
                        new
                        {
                            Id = 123,
                            Altura = 1.5,
                            Genero = "",
                            Nome = "Scyther",
                            Peso = 56.0,
                            Tipo = "[0,7]"
                        },
                        new
                        {
                            Id = 124,
                            Altura = 1.3999999999999999,
                            Genero = "",
                            Nome = "Jynx",
                            Peso = 40.600000000000001,
                            Tipo = "[11,14]"
                        },
                        new
                        {
                            Id = 125,
                            Altura = 1.1000000000000001,
                            Genero = "",
                            Nome = "Electabuzz",
                            Peso = 30.0,
                            Tipo = "[3]"
                        },
                        new
                        {
                            Id = 126,
                            Altura = 1.3,
                            Genero = "",
                            Nome = "Magmar",
                            Peso = 44.5,
                            Tipo = "[6]"
                        },
                        new
                        {
                            Id = 127,
                            Altura = 1.5,
                            Genero = "",
                            Nome = "Pinsir",
                            Peso = 55.0,
                            Tipo = "[0]"
                        },
                        new
                        {
                            Id = 128,
                            Altura = 1.3999999999999999,
                            Genero = "",
                            Nome = "Tauros",
                            Peso = 88.400000000000006,
                            Tipo = "[12]"
                        },
                        new
                        {
                            Id = 129,
                            Altura = 0.90000000000000002,
                            Genero = "",
                            Nome = "Magikarp",
                            Peso = 10.0,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 130,
                            Altura = 6.5,
                            Genero = "",
                            Nome = "Gyarados",
                            Peso = 235.0,
                            Tipo = "[17,7]"
                        },
                        new
                        {
                            Id = 131,
                            Altura = 2.5,
                            Genero = "",
                            Nome = "Lapras",
                            Peso = 220.0,
                            Tipo = "[17,11]"
                        },
                        new
                        {
                            Id = 132,
                            Altura = 0.29999999999999999,
                            Genero = "",
                            Nome = "Ditto",
                            Peso = 4.0,
                            Tipo = "[12]"
                        },
                        new
                        {
                            Id = 133,
                            Altura = 0.29999999999999999,
                            Genero = "",
                            Nome = "Eevee",
                            Peso = 6.5,
                            Tipo = "[12]"
                        },
                        new
                        {
                            Id = 134,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Vaporeon",
                            Peso = 29.0,
                            Tipo = "[17]"
                        },
                        new
                        {
                            Id = 135,
                            Altura = 0.80000000000000004,
                            Genero = "",
                            Nome = "Jolteon",
                            Peso = 24.5,
                            Tipo = "[3]"
                        },
                        new
                        {
                            Id = 136,
                            Altura = 0.90000000000000002,
                            Genero = "",
                            Nome = "Flareon",
                            Peso = 25.0,
                            Tipo = "[6]"
                        },
                        new
                        {
                            Id = 137,
                            Altura = 0.80000000000000004,
                            Genero = "",
                            Nome = "Porygon",
                            Peso = 36.5,
                            Tipo = "[12]"
                        },
                        new
                        {
                            Id = 138,
                            Altura = 0.40000000000000002,
                            Genero = "",
                            Nome = "Omanyte",
                            Peso = 7.5,
                            Tipo = "[15,17]"
                        },
                        new
                        {
                            Id = 139,
                            Altura = 1.0,
                            Genero = "",
                            Nome = "Omastar",
                            Peso = 35.0,
                            Tipo = "[15,17]"
                        },
                        new
                        {
                            Id = 140,
                            Altura = 0.5,
                            Genero = "",
                            Nome = "Kabuto",
                            Peso = 11.5,
                            Tipo = "[15,17]"
                        },
                        new
                        {
                            Id = 141,
                            Altura = 1.3,
                            Genero = "",
                            Nome = "Kabutops",
                            Peso = 40.5,
                            Tipo = "[15,17]"
                        },
                        new
                        {
                            Id = 142,
                            Altura = 1.8,
                            Genero = "",
                            Nome = "Aerodactyl",
                            Peso = 59.0,
                            Tipo = "[15,7]"
                        },
                        new
                        {
                            Id = 143,
                            Altura = 2.1000000000000001,
                            Genero = "",
                            Nome = "Snorlax",
                            Peso = 460.0,
                            Tipo = "[12]"
                        },
                        new
                        {
                            Id = 144,
                            Altura = 1.7,
                            Genero = "",
                            Nome = "Articuno",
                            Peso = 55.399999999999999,
                            Tipo = "[11,7]"
                        },
                        new
                        {
                            Id = 145,
                            Altura = 1.6000000000000001,
                            Genero = "",
                            Nome = "Zapdos",
                            Peso = 52.600000000000001,
                            Tipo = "[3,7]"
                        },
                        new
                        {
                            Id = 146,
                            Altura = 2.0,
                            Genero = "",
                            Nome = "Moltres",
                            Peso = 60.0,
                            Tipo = "[6,7]"
                        },
                        new
                        {
                            Id = 147,
                            Altura = 1.8,
                            Genero = "",
                            Nome = "Dratini",
                            Peso = 3.2999999999999998,
                            Tipo = "[2]"
                        },
                        new
                        {
                            Id = 148,
                            Altura = 4.0,
                            Genero = "",
                            Nome = "Dragonair",
                            Peso = 16.5,
                            Tipo = "[2]"
                        },
                        new
                        {
                            Id = 149,
                            Altura = 2.2000000000000002,
                            Genero = "",
                            Nome = "Dragonite",
                            Peso = 210.0,
                            Tipo = "[2,7]"
                        },
                        new
                        {
                            Id = 150,
                            Altura = 2.0,
                            Genero = "",
                            Nome = "Mewtwo",
                            Peso = 122.0,
                            Tipo = "[14]"
                        },
                        new
                        {
                            Id = 151,
                            Altura = 0.40000000000000002,
                            Genero = "",
                            Nome = "Mew",
                            Peso = 4.0,
                            Tipo = "[14]"
                        });
                });

            modelBuilder.Entity("PokemonApi.Models.Treinador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Insignias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_TREINADORES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Insignias = "[0]",
                            Nome = "Brock",
                            Regiao = "Kanto"
                        },
                        new
                        {
                            Id = 2,
                            Insignias = "[1]",
                            Nome = "Misty",
                            Regiao = "Kanto"
                        },
                        new
                        {
                            Id = 3,
                            Insignias = "[2]",
                            Nome = "Sg. Surge",
                            Regiao = "Kanto"
                        },
                        new
                        {
                            Id = 4,
                            Insignias = "[3]",
                            Nome = "Erika",
                            Regiao = "Kanto"
                        },
                        new
                        {
                            Id = 5,
                            Insignias = "[4]",
                            Nome = "Koga",
                            Regiao = "Kanto"
                        },
                        new
                        {
                            Id = 6,
                            Insignias = "[5]",
                            Nome = "Sabrina",
                            Regiao = "Kanto"
                        },
                        new
                        {
                            Id = 7,
                            Insignias = "[6]",
                            Nome = "Blaine",
                            Regiao = "Kanto"
                        },
                        new
                        {
                            Id = 8,
                            Insignias = "[7]",
                            Nome = "Giovanni",
                            Regiao = "Kanto"
                        });
                });

            modelBuilder.Entity("PokemonApi.Models.TreinadorPokemon", b =>
                {
                    b.Property<int>("TreinadorId")
                        .HasColumnType("int");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int?>("Ataque")
                        .HasColumnType("int");

                    b.Property<int?>("Defesa")
                        .HasColumnType("int");

                    b.Property<int>("Habilidade1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Habilidade2Id")
                        .HasColumnType("int");

                    b.Property<int?>("Habilidade3Id")
                        .HasColumnType("int");

                    b.Property<int?>("Habilidade4Id")
                        .HasColumnType("int");

                    b.Property<int?>("Nivel")
                        .HasColumnType("int");

                    b.Property<int?>("Velocidade")
                        .HasColumnType("int");

                    b.Property<int?>("Vida")
                        .HasColumnType("int");

                    b.HasKey("TreinadorId", "PokemonId");

                    b.HasIndex("PokemonId");

                    b.ToTable("TB_TREINADORES_POKEMONS", (string)null);

                    b.HasData(
                        new
                        {
                            TreinadorId = 1,
                            PokemonId = 74,
                            Habilidade1Id = 1,
                            Habilidade2Id = 40,
                            Nivel = 12
                        },
                        new
                        {
                            TreinadorId = 1,
                            PokemonId = 95,
                            Habilidade1Id = 1,
                            Habilidade2Id = 30,
                            Habilidade3Id = 54,
                            Habilidade4Id = 39,
                            Nivel = 14
                        });
                });

            modelBuilder.Entity("PokemonApi.Models.TreinadorPokemon", b =>
                {
                    b.HasOne("PokemonApi.Models.Pokemon", "Pokemon")
                        .WithMany("TreinadorPokemons")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonApi.Models.Treinador", "Treinador")
                        .WithMany("TreinadorPokemons")
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("PokemonApi.Models.Pokemon", b =>
                {
                    b.Navigation("TreinadorPokemons");
                });

            modelBuilder.Entity("PokemonApi.Models.Treinador", b =>
                {
                    b.Navigation("TreinadorPokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
